configs:
- id: training
  config:
    name:
      name: Appname
      type: environment
    parameters:
      mzid:
        configId: mz-1
        configType: management-zone
        property: id
        type: reference
    template: training.json
    skip: false
  type:
    api: maintenance-window
