configs:
- id: notification-1
  config:
    name:
      name: Appname
      type: environment
    parameters:
      alertingprofileId:
        configId: profile-1
        configType: alerting-profile
        property: id
        type: reference
      email:
        name: Email
        type: environment
    template: lab-notification.json
    skip: false
  type:
    api: notification
